version: '3'
services:
  db:
    image: mysql:8.0
    ports:
      - '3334:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'docker'
      MYSQL_PASSWORD: 'docker'
      MYSQL_DATABASE: 'test_db'
      TZ: 'Asia/Tokyo'
    volumes:
      - db-store:/var/lib/mysql
      - ./docker/mysql/sql:/docker-entrypoint-initdb.d

  voicevox_engine:
    image: voicevox/voicevox_engine:cpu-ubuntu20.04-latest
    ports:
      - '50021:50021'
    tty: true

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: 'mysql://docker:docker@db:3306/test_db'
    depends_on:
      - db
volumes:
  db-store:
